# Generated by Django 4.1.3 on 2022-12-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_of_post',
            field=models.CharField(choices=[('NW', 'новость'), ('PS', 'статья')], default='PS', max_length=2),
        ),
    ]
