# Generated by Django 4.1.4 on 2023-01-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('News', 'News'), ('Blog', 'Blog')], default='Blog', max_length=255),
        ),
    ]
