# Generated by Django 4.1.3 on 2023-01-16 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_appointment_remove_category_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_user',
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
