# Generated by Django 4.1.3 on 2023-01-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_category_sub_user_category_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribersUsers',
        ),
    ]
