# Generated by Django 4.1.4 on 2023-01-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_post_type'),
        ('news', '0007_delete_subscribersusers'),
        ('news', '0007_newscreated'),
    ]

    operations = [
    ]
