# Generated by Django 4.1.4 on 2023-01-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_merge_20230124_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercategory',
            name='sub_categories',
        ),
        migrations.RemoveField(
            model_name='usercategory',
            name='sub_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.DeleteModel(
            name='NewsCreated',
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]
